language: crystal
sudo: required
crystal:
    - latest
before_install:
  - sudo apt-get install gsl-bin libgsl-dev -y
install:
  - shards install
script:
  - crystal tool format --check
  - crystal build ./src/gsl.cr
  - crystal ./spec/gsl_spec.cr
branches:
  only:
    - test
